behaviors:
  CarAgent:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 128
      buffer_size: 1280
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 256
      num_layers: 2

    # Trainer configurations common to all trainers
    max_steps: 3e5
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 100
    checkpoint_interval: 50000
    threaded: false
    init_path: null
torch_settings:
  device: cuda
